name: 'Chromatic'
on: push
jobs:
    chromatic-deployment:
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v1
            - name: Install dependencies
              working-directory: packages/components
              run: yarn
            - name: Publish to Chromatic
              uses: chromaui/action@v1
              with:
                  workingDir: packages/components
                  token: ${{ secrets.GITHUB_TOKEN }}
                  projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
