name: Tests
on: [push]
jobs:
    test-hooks:
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: '15'
            - name: 'Test hooks'
              working-directory: ./packages/hooks
              run: |
                  yarn install
                  yarn test
