name: test
on: [push]
jobs:
    test-contracts:
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: '15'
            - name: 'Test frontend'
              working-directory: ./examples/frontend
              run: yarn install
            - name: 'Test contracts'
              working-directory: ./packages/contracts
              run: |
                  yarn install
                  yarn test
