name: test
on: [push]
jobs:
    test-contracts:
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: '15'
            - working-directory: ./examples/frontend
                run: yarn install
            - working-directory: ./packages/components
                run: yarn install
                run: yarn test
